### ISSUE TITLE
[Linux] Library overwrite.

### ISSUE THREAD

**Issue by comwizz2** [olegtarasov/FastText.NetWrapper#10]
I am needing to use this in a Centos 7 environment. 
The bundled Linux so is built against a newer version of glibc
I had to build my own, but when the app launches it overwrites my custom lib, I am forced to do some trickery with ld preload to make it work.

**Comment by olegtarasov** [comment]
Hi! Yes, I'm aware of this kind of problem. It really wasn't a priority, so it remains unfixed as of yet. There are two ways to fix it:

1. A quick fix. Add a flag `loadLibraryExplicit = true` to `FastTextWrapper` and if false, don't load the library explicitly. You would then be responsible for bundling the correct version of the native binary with your binary.
2. The correct way. Compile different versions of the native binary and bundle them. Check the glibc version at startup and extract the correct binary. There are two problems with that:
    * I'm not that good with linux, and will need to research the way to check glibc version.
    * Setting up the correct build insfrastructure will require some time.
    * The resulting NuGet package would increase in size even more :(

**Comment by ruozeng-w** [comment]
@olegtarasov hi~, I had the same problem, and I built my own .so file with gcc 4.8.5, then it says "Unable to find an entry point named 'CreateFastText' in shared library fasttext", actually, most of native apis declared in FastTextWrapper.Api.cs can not be found in fasttext.h. Did you use the original source code of fasttext to build [FastText.Native.xxx] packages? thx~

**Comment by ruozeng-w** [comment]
Never mind, I've found your fork and it works well

**Comment by olegtarasov** [comment]
Added a `useBundledLibrary` argument to `FastTextWrapper` constructor so that a custom-built native binary could be supplied.
