### ISSUE TITLE
Different results from the command line fasttext

### ISSUE THREAD

**Issue by sidc** [olegtarasov/FastText.NetWrapper#14]
I built a model from wikipedia dump. When I run the nearest neighbor call with fasttext-0.9.1 cmd line, I get different results than the FastText Nuget Netwrapper. For example these are the results for query "primeobsession" from the cmd line: 
whatsyourobsession 0.79625
thrillersacd 0.769539                                                                                                   
shiftinaction 0.764332                                                                                                  
andydehnart 0.764045                                                                                                    
secretstory 0.761035                                                                                                    
digitallyobsessed 0.76042                                                                                               confrontmagazine 0.758854                                                                                               comicaddiction 0.756743                                                                                                 
thrilljockey 0.756244                                                                                                   
marchmadness 0.754537                      

Whereas the following are the results from the NetWrapper: 

  | Name | Value | Type
-- | -- | -- | --
  | Label | "francisrimbert" | string
  | Probability | 0.767542958 | float
◢ | [1] | {FastText.NetWrapper.Prediction} | FastText.NetWrapper.Prediction
  | Label | "dbernard" | string
  | Probability | 0.762311339 | float
◢ | [2] | {FastText.NetWrapper.Prediction} | FastText.NetWrapper.Prediction
  | Label | "urgentessays" | string
  | Probability | 0.762221634 | float
◢ | [3] | {FastText.NetWrapper.Prediction} | FastText.NetWrapper.Prediction
  | Label | "danielravennest" | string
  | Probability | 0.7606867 | float
◢ | [4] | {FastText.NetWrapper.Prediction} | FastText.NetWrapper.Prediction
  | Label | "netknowledgenow" | string
  | Probability | 0.753572464 | float
◢ | [5] | {FastText.NetWrapper.Prediction} | FastText.NetWrapper.Prediction
  | Label | "wilkpedia" | string
  | Probability | 0.7532526 | float
◢ | [6] | {FastText.NetWrapper.Prediction} | FastText.NetWrapper.Prediction
  | Label | "sorfernando" | string
  | Probability | 0.745988 | float
◢ | [7] | {FastText.NetWrapper.Prediction} | FastText.NetWrapper.Prediction
  | Label | "orlandoferrer" | string
  | Probability | 0.7453338 | float
◢ | [8] | {FastText.NetWrapper.Prediction} | FastText.NetWrapper.Prediction
  | Label | "esperanzadirector" | string
  | Probability | 0.7446482 | float
◢ | [9] | {FastText.NetWrapper.Prediction} | FastText.NetWrapper.Prediction
  | Label | "universaltennis" | string
  | Probability | 0.74298507 | float
◢ | [10] | {FastText.NetWrapper.Prediction} | FastText.NetWrapper.Prediction
  | Label | "musewiki" | string
  | Probability | 0.742397249 | float

Is the FastText NetWrapper using a different version of FastText?

**Comment by TechnikEmpire** [comment]
Almost certainly, because 0.9.1 is almost 2 years old. I've manually rewritten fastText into a fully managed library and there's quite a few minor bugs they've fixed over the years that drastically affect output so its perfectly normal to see fluctuations between older and newer versions. My 2 cents.

**Comment by TechnikEmpire** [comment]
My bad, it's a year old.

**Comment by sidc** [comment]
My bad about the version. I have the latest FastText from their git repository. The results from the command line are the same.

**Comment by TechnikEmpire** [comment]
Hmmmm, for whatever reason, it looks like this library only ever called the GetNN (nearest neighbour) function inside of FastText, which is only used for analogies afaik. 

The repo owner forked fastText and added a CAPI that this lib pinvokes and that capi only ever calls getNN when it should be calling PredictLine and let the model classify based on the model parameters.

**Comment by TechnikEmpire** [comment]
It appears that they're incorrectly calling getNN and then returning categories based on the returned category index which isn't proper.  It should simply invoke the FastText::predictLine function.

Forgive me I'm wrong, I've just checked on my phone only.

**Comment by olegtarasov** [comment]
Hi @sidc!

Sorry for the late reply. This library uses custom-built fastText binary, which quite closely follows the `master` branch of official fastText repository. The fact that you use `0.9.1` binary and get different results from `nn` is weird.

I've just tried to train an unsupervised model with latest fastText bin from `master` (`0.9.2`) and then query nearest neighbours from that binary and from the .NET wrapper (which uses `0.9.1`). The results are identical:

```
Query word? slow
low 0.999476
overcooked 0.998307
hours 0.998296
cookbook 0.998271
cookbooks 0.998237
```

```
[0] = {FastText.NetWrapper.Prediction}
 Label = {string} "low"
 Probability = {float} 0.999475658
[1] = {FastText.NetWrapper.Prediction}
 Label = {string} "overcooked"
 Probability = {float} 0.99830699
[2] = {FastText.NetWrapper.Prediction}
 Label = {string} "hours"
 Probability = {float} 0.99829638
[3] = {FastText.NetWrapper.Prediction}
 Label = {string} "cookbook"
 Probability = {float} 0.998271048
[4] = {FastText.NetWrapper.Prediction}
 Label = {string} "cookbooks"
 Probability = {float} 0.998237133
```

Can you describe your test case with maximum detail, so I would try to reproduce it?
