### ISSUE TITLE
Missing the "test" function from original fasttext library

### ISSUE THREAD

**Issue by Vic281** [olegtarasov/FastText.NetWrapper#15]
The original fasttext library provides a test method to test the accuracy of a classification model, which calculates the precission and recall of a model.

Command example:

fasttext test model_cooking.bin cooking.valid

Output:

N  3000
P@1  0.164
R@1  0.0717
Number of examples: 3000

I miss this very important method in the FasttextNetWrapper. Is it possible to implement that?

**Comment by olegtarasov** [comment]
Hi @Vic281!

Yes, this function is missing from the wrapper. I have plans for adding it, but unfortunately I don't know when I will get to it. I would always appreciate a pull request :)

**Comment by olegtarasov** [comment]
@Vic281 I've just pushed version `1.1.0`, which among other things has an ability to test supervised models. Please see the `README` for details.
