### ISSUE TITLE
Trainintg callbacks?

### ISSUE THREAD

**Issue by VZMDeadAngel** [olegtarasov/FastText.NetWrapper#23]
Hi!

I would like to display the current training status in the model in a different interface than in the console.
Need to get time to finish.
Is this functionality planned?

**Comment by olegtarasov** [comment]
Hi @VZMDeadAngel! No, this kind of feature is not planned at the moment, but you are more than welcome to contribute a pull request. There is already a callback mechanism in low-level `void FastText::train(const Args& args, const TrainCallback& callback)` function, so it just needs to be surfaced to C#.

**Comment by olegtarasov** [comment]
I finally had some time on my hands and implemented training and autotune callbacks. Download release `1.2.4` and see the Readme for instructions!
