### ISSUE TITLE
Source for FastText.dll

### ISSUE THREAD

**Issue by sbrijl** [olegtarasov/FastText.NetWrapper#4]
Did you modify the source code for the fastText binary? When I try to compile my own version of the .dll and include it as a resource, then the call to CreateFastText() seems to fail. 

If you modified any of the c++ classes/headers for the import can you maybe share the source file?

Thanks.

**Comment by olegtarasov** [comment]
Hi! Sorry for the late reply — I didn't get the notification for some reason. Yes, I modified original FastText by adding a bunch of C exports. You can get the code at my FastText fork: https://github.com/olegtarasov/fastText. You need the branch “vcpp”. https://github.com/olegtarasov/fastText/tree/vcpp/src/Vs2017 contains the solution that builds the library.

**Comment by sbrijl** [comment]
Thanks, that is exactly what I was looking for.

Sorry that I didn't think to check if you had that in the repository elsewhere.

**Comment by sbrijl** [comment]
By the way, it might interest you to know, in case you missed it, that they just published in December a OneVersusAll variant for multiple labels (which was the nature of the changes I wanted to include in my own compiled library for FastText:

https://github.com/facebookresearch/fastText/releases/tag/v0.2.0

**Comment by olegtarasov** [comment]
Yeah, I've got around to merging the upstream code just today, so I'm analyzing new methods right now. I think I will push an updated wrapper in a couple of days.

Thanks!

**Comment by sbrijl** [comment]
Hey Oleg,

I can't really see how to pass the OVA argument for a supervised training without changing some stuff in the wrapper's source. Am I missing something? Do you have an example. The current util seems to use softmax, even when I use "low-level" and change the arguments to model=supervised and loss=OVA.
