### ISSUE TITLE
Support for non-windows environments

### ISSUE THREAD

**Issue by grenville84** [olegtarasov/FastText.NetWrapper#5]
Hi Oleg, great work with the wrapper. I am looking at integrating it into another project, that is .NET Core, so I took the code and updated to .NET Standard 2.

It was working great until I put it into a linux docker container, then was hitting this error;

Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'kernel32.dll' or one of its dependencies. I can understand that it won't work with the [DllImport("kernel32.dll")] LoadLibraryEx... invoke because that is Windows specific. I'm researching what's involved in modifying it to run on Linux. Any idea if there's a solution to that?

Cheers!

**Comment by olegtarasov** [comment]
Hi!

Porting this library to Linux isn't that straightforward. Ass you know, FastText library is originally written in C. There is no exported API to be called from .NET, so I had to make my own fork of FastText and add a bunch of exported functions: https://github.com/olegtarasov/fastText (see the `vcpp` branch). These exports are designed to be used only under Windows right now. Moreover, FastTextWrapper contains binary version of this modified FastText library compiled for Windows, as a resource. LoadLibrary is also there to guarantee correct unpacking and loading under ASP .NET.

So as far as I can see the task of porting this wrapper to Linux consists of the following steps:

1. Make FastText exported functions cross-platform and compile a binary for linux.
2. Include linux binary as a resource in the wrapper.
3. Extract the correct binary under each OS.
4. Under Linux don't use LoadLibrary, and jut use plain P/Invoke Import syntax.

As you can see, this task is quite time-consuming and also needs some research, so I don't think I will be able to port this to Linux in the nearest future.

**Comment by olegtarasov** [comment]
Similar to #1

**Comment by grenville84** [comment]
Hi Oleg,

Thanks for the reply. A c++ proficient friend helped out and managed to get it working on both platforms with platform detection.

We found your customised c++ source, and removed the windows specific elements, then compiled a .so file for Linux. Then we used a libraryloader package to point to the different entry points (had to use delegates).

Also updated to use .net standard so we now have it in use in a .net core 2.2 app running in a Linux container.

Very tricky but worth it. I'll post the source code asap.

Thanks,
Nick

**Comment by olegtarasov** [comment]
@grenville84 Hi! This is fantastic news! Is there any chance you can do a pull request into https://github.com/olegtarasov/fastText and into this repo? Having Linux support in this wrapper would great :)

**Comment by grenville84** [comment]
Sure, will do! The only issue could be 5he size of the Linux binary is around 300MB. So combined with the windows dll which is around 200, it adds up to a lot. It's not a problem for us and we like it being able to detect platform and work on both, but maybe some people would prefer to have a platform specific version with lower package size.

I'll do a PR anyway and you can decode :)
Would you also like a PR for the c++ source changes too.

**Comment by olegtarasov** [comment]
Yes, having a PR for the C++ changes would be great too! C++ sources are in https://github.com/olegtarasov/fastText repo, `vcpp` branch. I wonder, why linux binaries are so large — maybe I will find a way to make them smaller (it will be a nice intro into linux programming for me :) )

Thank you!
