### ISSUE TITLE
cooking.train.txt

### ISSUE THREAD

**Issue by agatlin** [olegtarasov/FastText.NetWrapper#6]
Where is the cooking.train.txt sample file which is mentioned in the text?

Also, are you open to pull requests for a few minor tweaks?

**Comment by olegtarasov** [comment]
Hi @agatlin!

Sorry for the late reply. `cooking.train.txt` is from FastText supervised tutorial: https://github.com/facebookresearch/fastText/blob/master/docs/supervised-tutorial.md.

Yes, I'm open to pull requests :)
