### ISSUE TITLE
how to retrain model incrementally

### ISSUE THREAD

**Issue by hnlinn** [olegtarasov/FastText.NetWrapper#9]
Will appreciate to know how to train a model incrementally. 
Tried the below link. but it is now working. 

Link 
https://github.com/facebookresearch/fastText/pull/423
command
./fasttext [supervised | skipgram | cbow] -input train.data -inputModel trained.model.bin -output re-trained [other options] -incr

Thanks in advances

**Comment by olegtarasov** [comment]
Hi @hnlinn! That pull request was never merged to the official codebase, so it's not supported in this wrapper either.

**Comment by hnlinn** [comment]
Thanks. @olegtarasov
